/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    services: Service;
    'solution-categories': SolutionCategory;
    'case-studies': CaseStudy;
    'team-members': TeamMember;
    testimonials: Testimonial;
    'process-steps': ProcessStep;
    values: Value;
    faqs: Faq;
    engagements: Engagement;
    'project-pricing': ProjectPricing;
    submissions: Submission;
    bookings: Booking;
    quotes: Quote;
    'page-views': PageView;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    services: ServicesSelect<false> | ServicesSelect<true>;
    'solution-categories': SolutionCategoriesSelect<false> | SolutionCategoriesSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'process-steps': ProcessStepsSelect<false> | ProcessStepsSelect<true>;
    values: ValuesSelect<false> | ValuesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    engagements: EngagementsSelect<false> | EngagementsSelect<true>;
    'project-pricing': ProjectPricingSelect<false> | ProjectPricingSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    'page-views': PageViewsSelect<false> | PageViewsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    features: Feature;
    'booking-settings': BookingSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    features: FeaturesSelect<false> | FeaturesSelect<true>;
    'booking-settings': BookingSettingsSelect<false> | BookingSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * The disciplines listed on the homepage and services page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  /**
   * Used in the page link, e.g. performance-marketing
   */
  slug: string;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * A YouTube or Vimeo link. Leave blank if you upload a file below.
   */
  videoUrl?: string | null;
  videoFile?: (number | null) | Media;
  /**
   * Used as the player title for screen readers.
   */
  videoTitle?: string | null;
  /**
   * Every published service appears on the Services page; ticked ones also appear on the homepage.
   */
  core?: boolean | null;
  /**
   * One or two lines, shown on the homepage card.
   */
  short: string;
  /**
   * What is going wrong for a business before they come to you. Shown first on the service page (brief §21).
   */
  problem?: string | null;
  /**
   * How Zirka solves that problem. Also shown on the services page.
   */
  description: string;
  /**
   * e.g. "Typical engagement: 3.2–4.1× ROAS in two quarters."
   */
  outcomes?: string | null;
  capabilities?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Questions specific to this service. Answer honestly — never promise rankings, revenue or results (brief §14). The section is hidden while empty.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Photo shown behind the colour wash on the card.
   */
  image?: (number | null) | Media;
  /**
   * Which brand colour wash sits over the photo.
   */
  accent?: ('plate-1' | 'plate-2' | 'plate-3' | 'plate-4') | null;
  icon?: ('target' | 'compass' | 'network' | 'prism') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and search engines.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * The four headline categories on the homepage, the Services page and the Services menu. Pick which services belong to each.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solution-categories".
 */
export interface SolutionCategory {
  id: number;
  /**
   * e.g. "Get Found"
   */
  name: string;
  /**
   * Used in links, e.g. "get-found" gives /services#get-found. Lowercase and hyphens only.
   */
  slug: string;
  /**
   * One or two sentences on the outcome, not the tasks.
   */
  description: string;
  /**
   * The services shown under this category. A service can sit in more than one.
   */
  services?: (number | Service)[] | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Client work shown on the homepage, the work page, and each case study's own page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  /**
   * Client name.
   */
  name: string;
  /**
   * e.g. "Skincare · Performance"
   */
  category: string;
  /**
   * The headline result, e.g. "3.2× ROAS in 90 days". Real, documented results only — it is never shown on a Concept Project.
   */
  metric: string;
  /**
   * One line on what you did.
   */
  summary: string;
  image?: (number | null) | Media;
  accent?: ('w1' | 'w2' | 'w3' | 'w4' | 'w5' | 'w6') | null;
  /**
   * Where the client was stuck when they came to you.
   */
  challenge?: string | null;
  /**
   * What you did, and why that and not something else.
   */
  approach?: string | null;
  servicesUsed?: (number | Service)[] | null;
  /**
   * How long the work ran, e.g. "3 months" or "Jan – Apr 2026".
   */
  timeframe?: string | null;
  /**
   * What changed for the business, in words.
   */
  outcome?: string | null;
  /**
   * Up to four headline numbers for the results strip.
   */
  results?:
    | {
        /**
         * e.g. "3.2×"
         */
        value: string;
        /**
         * e.g. "Return on ad spend"
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * In the client's own words. Only use a quote they actually gave you.
   */
  testimonialQuote?: string | null;
  /**
   * e.g. "Priya Raman, Marketing Director"
   */
  testimonialAttribution?: string | null;
  /**
   * The page address, e.g. /work/solace-skincare. Filled in from the name automatically.
   */
  slug?: string | null;
  /**
   * Lower numbers appear first. The first one is the featured card.
   */
  order?: number | null;
  /**
   * Tick this for anything that is not genuine, documented client work. The site then labels it a Concept Project and hides every result, timeframe and testimonial, so a concept can never read as a client outcome.
   */
  sample?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Real team members only — never stock, AI-generated or placeholder people (brief §3). Someone appears on the site only when they are published, have a real photo, and Features → Leadership is switched on.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  /**
   * Job title, e.g. "Head of Performance Media"
   */
  role: string;
  order?: number | null;
  /**
   * A real photo of this person — square crops work best. Without one they are not shown, rather than showing a placeholder.
   */
  photo?: (number | null) | Media;
  /**
   * Two or three sentences, in plain language.
   */
  bio?: string | null;
  /**
   * e.g. "Eight years running paid search for retail brands."
   */
  experience?: string | null;
  /**
   * Only certifications this person actually holds and can show.
   */
  certifications?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  linkedin?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Genuine testimonials only, supplied by the client (brief §7) — never written for them. Published ones appear on the homepage when Features → Testimonial is on.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  name: string;
  /**
   * e.g. "Chief Marketing Officer"
   */
  role?: string | null;
  company: string;
  /**
   * Optional, and only with their permission.
   */
  photo?: (number | null) | Media;
  /**
   * Optional, and only with their permission.
   */
  logo?: (number | null) | Media;
  /**
   * Optional, and only if documented, e.g. "42% more enquiries in 3 months".
   */
  result?: string | null;
  /**
   * Optional link to the full story.
   */
  caseStudy?: (number | null) | CaseStudy;
  /**
   * Shown first when there is more than one.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The "How we work" stages on the homepage. Order matters — they read as a sequence.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process-steps".
 */
export interface ProcessStep {
  id: number;
  /**
   * e.g. "Chart"
   */
  name: string;
  description: string;
  /**
   * Numbering on the site follows this order.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The operating principles shown on the about page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "values".
 */
export interface Value {
  id: number;
  name: string;
  description: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Pricing is restricted to admins and super admins.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "engagements".
 */
export interface Engagement {
  id: number;
  /**
   * e.g. "Zirka Growth"
   */
  name: string;
  /**
   * e.g. "From $950" or "Custom Quote"
   */
  price: string;
  /**
   * e.g. "per month" or "one-off scope"
   */
  cadence: string;
  summary: string;
  includes?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  /**
   * Highlights the tier and adds the "Most common" badge.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * One-off project prices. Restricted to admins and super admins.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-pricing".
 */
export interface ProjectPricing {
  id: number;
  /**
   * e.g. "Business Websites"
   */
  name: string;
  /**
   * e.g. "from $1,500"
   */
  price: string;
  /**
   * Optional one-line clarification shown under the name.
   */
  note?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Everything sent through the website's contact and free-audit forms, in one list. Filter by Type to see audit requests alone.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  kind?: ('enquiry' | 'audit') | null;
  name: string;
  email: string;
  phone?: string | null;
  company?: string | null;
  website?: string | null;
  goal?: string | null;
  budget?: string | null;
  message?: string | null;
  /**
   * Where this lead came from, captured from the link they arrived on. Only campaign tags and the referring site — never anything personal.
   */
  attribution?: {
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    utmContent?: string | null;
    utmTerm?: string | null;
    landingPage?: string | null;
    referrer?: string | null;
  };
  status?: ('new' | 'open' | 'won' | 'closed') | null;
  /**
   * Internal only — never shown on the website.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Consultations booked through the website. Times are stored in UTC and shown in your browser's timezone.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  start: string;
  end: string;
  status: 'confirmed' | 'completed' | 'no-show' | 'cancelled';
  name: string;
  email: string;
  phone?: string | null;
  company?: string | null;
  /**
   * What they want to talk about.
   */
  topic?: string | null;
  /**
   * The timezone they booked from.
   */
  visitorTimezone?: string | null;
  /**
   * Internal only.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Quote requests from the website, including the services each person asked about.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  company?: string | null;
  /**
   * What they asked us to quote for.
   */
  services?: (number | Service)[] | null;
  /**
   * The range they picked on the form, or a one-off project.
   */
  budget?: string | null;
  timeline?: string | null;
  details?: string | null;
  status?: ('new' | 'quoted' | 'won' | 'closed') | null;
  /**
   * Internal only.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Anonymous traffic log. No IP addresses or cookies are stored.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-views".
 */
export interface PageView {
  id: number;
  path: string;
  referrer?: string | null;
  session?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Super admins can set any role. Admins can only create and manage Workers.
   */
  role: 'superadmin' | 'admin' | 'worker';
  /**
   * Shown if this person appears on the public team section.
   */
  jobTitle?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'solution-categories';
        value: number | SolutionCategory;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'process-steps';
        value: number | ProcessStep;
      } | null)
    | ({
        relationTo: 'values';
        value: number | Value;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'engagements';
        value: number | Engagement;
      } | null)
    | ({
        relationTo: 'project-pricing';
        value: number | ProjectPricing;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null)
    | ({
        relationTo: 'page-views';
        value: number | PageView;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  order?: T;
  videoUrl?: T;
  videoFile?: T;
  videoTitle?: T;
  core?: T;
  short?: T;
  problem?: T;
  description?: T;
  outcomes?: T;
  capabilities?:
    | T
    | {
        label?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  image?: T;
  accent?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solution-categories_select".
 */
export interface SolutionCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  services?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  metric?: T;
  summary?: T;
  image?: T;
  accent?: T;
  challenge?: T;
  approach?: T;
  servicesUsed?: T;
  timeframe?: T;
  outcome?: T;
  results?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  testimonialQuote?: T;
  testimonialAttribution?: T;
  slug?: T;
  order?: T;
  sample?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  order?: T;
  photo?: T;
  bio?: T;
  experience?: T;
  certifications?:
    | T
    | {
        name?: T;
        id?: T;
      };
  linkedin?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  role?: T;
  company?: T;
  photo?: T;
  logo?: T;
  result?: T;
  caseStudy?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process-steps_select".
 */
export interface ProcessStepsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "values_select".
 */
export interface ValuesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "engagements_select".
 */
export interface EngagementsSelect<T extends boolean = true> {
  name?: T;
  price?: T;
  cadence?: T;
  summary?: T;
  includes?:
    | T
    | {
        label?: T;
        id?: T;
      };
  order?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-pricing_select".
 */
export interface ProjectPricingSelect<T extends boolean = true> {
  name?: T;
  price?: T;
  note?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  kind?: T;
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  website?: T;
  goal?: T;
  budget?: T;
  message?: T;
  attribution?:
    | T
    | {
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        utmContent?: T;
        utmTerm?: T;
        landingPage?: T;
        referrer?: T;
      };
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  start?: T;
  end?: T;
  status?: T;
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  topic?: T;
  visitorTimezone?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  services?: T;
  budget?: T;
  timeline?: T;
  details?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-views_select".
 */
export interface PageViewsSelect<T extends boolean = true> {
  path?: T;
  referrer?: T;
  session?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  jobTitle?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Brand details, hero copy and contact channels used across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName: string;
  slogan: string;
  /**
   * The small label above the hero headline.
   */
  descriptor?: string | null;
  heroHeadline: string;
  /**
   * Which word in the headline is picked out in copper.
   */
  heroEmphasis?: string | null;
  heroLede: string;
  heroImage?: (number | null) | Media;
  /**
   * e.g. "Zirka Digital Solutions LLC". Used in both documents.
   */
  legalEntity?: string | null;
  /**
   * e.g. "the State of Georgia, USA" or "Kenya".
   */
  legalJurisdiction?: string | null;
  termsIntro?: string | null;
  terms?:
    | {
        heading: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  refundsIntro?: string | null;
  refunds?:
    | {
        heading: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  videoHeading?: string | null;
  videoIntro?: string | null;
  /**
   * A YouTube or Vimeo link. Leave blank if you upload a file below.
   */
  videoUrl?: string | null;
  videoFile?: (number | null) | Media;
  videoPoster?: (number | null) | Media;
  /**
   * The headline at the top of the about page.
   */
  aboutTitle?: string | null;
  aboutLede?: string | null;
  storyHeading?: string | null;
  /**
   * Tell visitors who you are and why you started. Leave empty to hide this section.
   */
  story?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  storyImage?: (number | null) | Media;
  /**
   * Digits only, including country code — used for the wa.me link.
   */
  whatsapp?: string | null;
  phoneDisplay?: string | null;
  email?: string | null;
  socialHandle?: string | null;
  hours?: string | null;
  /**
   * The four figures under the hero.
   */
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  trustedBy?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  whoWeHelp?: {
    heading?: string | null;
    body?: string | null;
    /**
     * Optional. Shown as a row of tags under the text.
     */
    industries?:
      | {
          name: string;
          id?: string | null;
        }[]
      | null;
  };
  projectPricingNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Turn parts of the website on or off. Changes apply as soon as you save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features".
 */
export interface Feature {
  id: number;
  /**
   * When on, every public page shows the maintenance notice instead. Search engines are told the site is temporarily unavailable, so your rankings are kept.
   */
  maintenanceMode?: boolean | null;
  maintenanceHeading?: string | null;
  maintenanceMessage?: string | null;
  /**
   * The four figures under the homepage headline.
   */
  showStats?: boolean | null;
  /**
   * The row of client names below the hero.
   */
  showTrustedBy?: boolean | null;
  /**
   * The four solution categories on the homepage.
   */
  showServices?: boolean | null;
  /**
   * The case studies on the homepage.
   */
  showWork?: boolean | null;
  /**
   * The large client quote (only appears if one is published).
   */
  showTestimonial?: boolean | null;
  /**
   * Who Zirka works with. Edit the wording under Site Settings → Who we help.
   */
  showWhoWeHelp?: boolean | null;
  /**
   * The numbered process steps.
   */
  showProcess?: boolean | null;
  /**
   * The engagement tiers and prices.
   */
  showPricing?: boolean | null;
  /**
   * Common questions.
   */
  showFaq?: boolean | null;
  /**
   * The homepage video. Only appears when a video is set under Site Settings → Homepage video.
   */
  showVideo?: boolean | null;
  /**
   * The operating principles.
   */
  showValues?: boolean | null;
  /**
   * The team members and their photos.
   */
  showLeadership?: boolean | null;
  /**
   * WhatsApp buttons in the hero and closing banners.
   */
  showWhatsApp?: boolean | null;
  /**
   * When off, the contact page shows your WhatsApp and details only.
   */
  contactFormEnabled?: boolean | null;
  /**
   * Let visitors pick services and request a quote from the website.
   */
  quotesEnabled?: boolean | null;
  /**
   * Let people book a free consultation from the website. Set your hours under Bookings → Booking Availability.
   */
  bookingEnabled?: boolean | null;
  /**
   * Anonymous page-view counting for the dashboard charts. Turning this off stops new data; existing data is kept.
   */
  analyticsEnabled?: boolean | null;
  /**
   * Email a notification for every new enquiry.
   */
  alertsEnabled?: boolean | null;
  /**
   * The inbox that receives new-enquiry alerts.
   */
  notifyEmail?: string | null;
  /**
   * e.g. smtp.gmail.com
   */
  smtpHost?: string | null;
  /**
   * 465 (SSL) or 587
   */
  smtpPort?: number | null;
  /**
   * Usually the full email address that sends.
   */
  smtpUser?: string | null;
  /**
   * For Gmail, an App Password — never your normal password. Visible only to super admins.
   */
  smtpPass?: string | null;
  /**
   * Leave blank to use the username.
   */
  fromAddress?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * When people can book a free consultation. Visitors see these times in their own timezone.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-settings".
 */
export interface BookingSetting {
  id: number;
  /**
   * Your working hours' timezone, e.g. "America/New_York" or "Africa/Nairobi".
   */
  timezone: string;
  callMinutes: number;
  bufferMinutes?: number | null;
  /**
   * No bookings sooner than this.
   */
  minNoticeHours?: number | null;
  daysAhead?: number | null;
  /**
   * Shown to the person booking, e.g. how the call happens.
   */
  meetingDetails?: string | null;
  /**
   * Add a row per block of availability. Use two rows for one day to leave a lunch break.
   */
  weeklyHours?:
    | {
        day: '1' | '2' | '3' | '4' | '5' | '6' | '0';
        start: string;
        end: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Holidays or days you're unavailable. No slots are offered on these dates.
   */
  blockedDates?:
    | {
        date: string;
        reason?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  slogan?: T;
  descriptor?: T;
  heroHeadline?: T;
  heroEmphasis?: T;
  heroLede?: T;
  heroImage?: T;
  legalEntity?: T;
  legalJurisdiction?: T;
  termsIntro?: T;
  terms?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  refundsIntro?: T;
  refunds?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  videoHeading?: T;
  videoIntro?: T;
  videoUrl?: T;
  videoFile?: T;
  videoPoster?: T;
  aboutTitle?: T;
  aboutLede?: T;
  storyHeading?: T;
  story?:
    | T
    | {
        text?: T;
        id?: T;
      };
  storyImage?: T;
  whatsapp?: T;
  phoneDisplay?: T;
  email?: T;
  socialHandle?: T;
  hours?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  trustedBy?:
    | T
    | {
        name?: T;
        id?: T;
      };
  whoWeHelp?:
    | T
    | {
        heading?: T;
        body?: T;
        industries?:
          | T
          | {
              name?: T;
              id?: T;
            };
      };
  projectPricingNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features_select".
 */
export interface FeaturesSelect<T extends boolean = true> {
  maintenanceMode?: T;
  maintenanceHeading?: T;
  maintenanceMessage?: T;
  showStats?: T;
  showTrustedBy?: T;
  showServices?: T;
  showWork?: T;
  showTestimonial?: T;
  showWhoWeHelp?: T;
  showProcess?: T;
  showPricing?: T;
  showFaq?: T;
  showVideo?: T;
  showValues?: T;
  showLeadership?: T;
  showWhatsApp?: T;
  contactFormEnabled?: T;
  quotesEnabled?: T;
  bookingEnabled?: T;
  analyticsEnabled?: T;
  alertsEnabled?: T;
  notifyEmail?: T;
  smtpHost?: T;
  smtpPort?: T;
  smtpUser?: T;
  smtpPass?: T;
  fromAddress?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-settings_select".
 */
export interface BookingSettingsSelect<T extends boolean = true> {
  timezone?: T;
  callMinutes?: T;
  bufferMinutes?: T;
  minNoticeHours?: T;
  daysAhead?: T;
  meetingDetails?: T;
  weeklyHours?:
    | T
    | {
        day?: T;
        start?: T;
        end?: T;
        id?: T;
      };
  blockedDates?:
    | T
    | {
        date?: T;
        reason?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}